### ISSUE TITLE
Unique validation with ar.

### ISSUE THREAD

**Issue by jeanali** [codezero-be/laravel-unique-translation#13]
Why unique validation does not work with Arabic language, but with English it's OK!

My code in store method:

<img width="934" alt="Screen Shot 2020-06-30 at 4 41 26 PM" src="https://user-images.githubusercontent.com/67483209/86133124-900e6000-baf0-11ea-8d9e-51302d9ad21d.png">

the database:
<img width="775" alt="Screen Shot 2020-06-30 at 4 38 30 PM" src="https://user-images.githubusercontent.com/67483209/86133210-ac120180-baf0-11ea-97c3-8cc3392bdc24.png">

**Comment by ivanvermeyen** [comment]
Hi,

It seems that it is not finding the backslash although both the database value and the search value are the same.
I'm still trying to find out why...

According to [this post](https://stackoverflow.com/questions/14926386/how-to-search-for-slash-in-mysql-and-why-escaping-not-required-for-wher) we need to escape a slash x4 when using a LIKE query, but adding slashes in the test didn't help... 

So looking further.

Any ideas are welcome :)

**Comment by jeanali** [comment]
Exactly, you right in search also( I can not search with Arabic words )

**Comment by ivanvermeyen** [comment]
I didn't add enough backslashes lol...

```php
$value = str_replace('\\', '\\\\\\\\', $value);
```

I had to escape the escaped backslashes so the resulting string still contains 4 escaped backslashes...
Nuts.

Commit incoming. 👍

**Comment by jeanali** [comment]
That's mean now upgrade my version and it would be works?(new on Github)😭

**Comment by jeanali** [comment]
After upgrading to last version !still does not works

Note: I don't know if you take this or not but there is no only 4 backslashes! Each letter in Arabic store backslashe before it 

<img width="956" alt="Screen Shot 2020-06-30 at 7 30 07 PM" src="https://user-images.githubusercontent.com/67483209/86151952-21d59780-bb08-11ea-9f0e-3b62197f93d2.png">

**Comment by RabeeaAli** [comment]
I have the same issue with Arabic lang! any slove yet?

**Comment by ivanvermeyen** [comment]
I can't reproduce the issue anymore in my tests...
Can you double check that you have v3.3.2?

This test passes for me:

```php
/** @test */
public function it_handles_backslashes_in_values()
{
    Model::create([
        'slug' => ['ar' => '\u0641\u0626\u0629'],
        'name' => ['ar' => '\u0641\u0626\u0629'],
    ]);

    $rules = [
        'slug.*' => "{$this->rule}:{$this->table}",
        'name.*' => UniqueTranslationRule::for($this->table),
    ];

    $validation = Validator::make([
        'slug' => ['ar' => '\u0641\u0626\u0629'],
        'name' => ['ar' => '\u0641\u0626\u0629'],
    ], $rules);

    $this->assertTrue($validation->fails());
}
```

**Comment by jeanali** [comment]
😞 

<img width="652" alt="Screen Shot 2020-06-30 at 9 32 20 PM" src="https://user-images.githubusercontent.com/67483209/86163652-3ec69680-bb19-11ea-97e2-650395e8a032.png">

**Comment by ivanvermeyen** [comment]
Still not working?
Can you give me some more context to work with?
What do your form fields look like?
Does the request data matches the expected value?

**Comment by jeanali** [comment]
My form:

<img width="786" alt="Screen Shot 2020-06-30 at 10 02 06 PM" src="https://user-images.githubusercontent.com/67483209/86166707-e34ad780-bb1d-11ea-9222-52b505639e01.png">


dd for the request( now I already has something called "جديد" in database in Arabic means new so when Add another "جديد" to database it's stored!

<img width="475" alt="Screen Shot 2020-06-30 at 10 05 03 PM" src="https://user-images.githubusercontent.com/67483209/86166747-f362b700-bb1d-11ea-8aa7-11d5f28020c3.png">


Store method:

<img width="762" alt="Screen Shot 2020-06-30 at 10 01 30 PM" src="https://user-images.githubusercontent.com/67483209/86166767-fbbaf200-bb1d-11ea-83c9-4ee5da7c860a.png">

**Comment by jeanali** [comment]
My form:
<img width="747" alt="Screen Shot 2020-06-30 at 10 18 07 PM" src="https://user-images.githubusercontent.com/67483209/86167654-9a941e00-bb1f-11ea-9962-720175d6f1b9.png">


dd for the request( now I already had something called "جديد" in database in Arabic means new so when Add another "جديد" to database it's `stored!`

` array:3 [▼
   "_token" => "7W9TdN3AcyjxwgfatCqyvuse6rZ656R3fPkbrV0E"
   "category_name" => array:2 [▼
     "ar" => "جديد"
     "en" => "new"
   ]
    "category_id" => "1"
   ]
`



Store method:

     ` public function store(Request $request)
       {
        $data = $request->validate([
            'category_name.*' => ['required','unique_translation:categories'],
            'category_id' => '',
        ],[],[
            'category_name.ar' => trans('site.category_nameـar'),
            'category_name.en' => trans('site.category_nameـen'),
        ]);

        Category::create([
            'category_name'=> $data['category_name'],
            'slug'=> Str::slug($data['category_name']['en']),
            'category_id'=>  $request->category_id
                            ? $data['category_id']
                            : NULL,
        ]);

        return redirect()->back()
            ->with('success',trans('site.message_added'));

    }`

**Comment by ivanvermeyen** [comment]
After further investigation...
 
This:

```php
Model::create([
    'slug' => ['ar' => '\u062c\u062f\u064a\u062f'],
    'name' => ['ar' => '\u062c\u062f\u064a\u062f'],
]);
```

is saved in the model with double slashes:

```php
  #attributes: array:3 [
    "slug" => "{"ar":"\\u062c\\u062f\\u064a\\u062f"}"
    "name" => "{"ar":"\\u062c\\u062f\\u064a\\u062f"}"
    "id" => 1
  ]
```

But this:

```php
Model::create([
    'slug' => ['ar' => 'جديد'],
    'name' => ['ar' => 'جديد'],
]);
```

is saved with single slashes:

```php
 #attributes: array:3 [
    "slug" => "{"ar":"\u062c\u062f\u064a\u062f"}"
    "name" => "{"ar":"\u062c\u062f\u064a\u062f"}"
    "id" => 1
  ]
```

Now this test works:

```php
/** @test */
public function it_handles_backslashes_in_values()
{
    Model::create([
        'slug' => ['ar' => '\u062c\u062f\u064a\u062f'],
        'name' => ['ar' => '\u062c\u062f\u064a\u062f'],
    ]);

    $rules = [
        'slug.*' => "{$this->rule}:{$this->table}",
        'name.*' => UniqueTranslationRule::for($this->table),
    ];

    $validation = Validator::make([
        'slug' => ['ar' => '\u062c\u062f\u064a\u062f'],
        'name' => ['ar' => '\u062c\u062f\u064a\u062f'],
    ], $rules);

    $this->assertTrue($validation->fails());
}
```

And also this one:

```php
/** @test */
public function it_handles_backslashes_in_values2()
{
    Model::create([
        'slug' => ['ar' => 'جديد'],
        'name' => ['ar' => 'جديد'],
    ]);

    $rules = [
        'slug.*' => "{$this->rule}:{$this->table}",
        'name.*' => UniqueTranslationRule::for($this->table),
    ];

    $validation = Validator::make([
        'slug' => ['ar' => 'جديد'],
        'name' => ['ar' => 'جديد'],
    ], $rules);

    $this->assertTrue($validation->fails());
}
```

But not this one, because the model adds double slashes:

```php
/** @test */
public function it_handles_backslashes_in_values3()
{
    Model::create([
        'slug' => ['ar' => '\u062c\u062f\u064a\u062f'],
        'name' => ['ar' => '\u062c\u062f\u064a\u062f'],
    ]);

    $rules = [
        'slug.*' => "{$this->rule}:{$this->table}",
        'name.*' => UniqueTranslationRule::for($this->table),
    ];

    $validation = Validator::make([
        'slug' => ['ar' => 'جديد'],
        'name' => ['ar' => 'جديد'],
    ], $rules);

    $this->assertTrue($validation->fails());
}
```

Since you don't have double slashes in the database, the 2nd test should apply to your use case, but at the moment I still don't know why it's not working on your end.
It could be a database collation problem, but I'm no expert on that.
Are your columns set to `utf8_general_ci` or something similar?

**Comment by jeanali** [comment]
Yep it's `utf8_general_ci`!

**Comment by ivanvermeyen** [comment]
Hi,

If I try to enter جديد as a value in a form of one of my projects this is what I end up seeing in the database:

If it is a `JSON` column:

<img width="82" alt="Schermafbeelding 2020-07-01 om 12 15 16" src="https://user-images.githubusercontent.com/3598622/86232812-cdc4c480-bb94-11ea-86d3-54a79768386e.png">

If it is a `TEXT` column:

<img width="219" alt="Schermafbeelding 2020-07-01 om 12 28 47" src="https://user-images.githubusercontent.com/3598622/86233925-7162a480-bb96-11ea-8baa-77f60f9e79e3.png">

In both cases, validation was working as expected here.
I'm using MySQL 5.7 here.

Not sure if it matters but this is the charset it is using:

<img width="310" alt="Schermafbeelding 2020-07-01 om 12 39 34" src="https://user-images.githubusercontent.com/3598622/86234970-03b77800-bb98-11ea-8096-fb847cc4b10f.png">

**Comment by jeanali** [comment]
Hey!
This is my coulmn!

<img width="978" alt="Screen Shot 2020-07-01 at 4 45 32 PM" src="https://user-images.githubusercontent.com/67483209/86251308-5f92f880-bbba-11ea-9499-5cd24ece497a.png">

**Comment by ivanvermeyen** [comment]
I see that your column is a `VARCHAR`.
Does it help if you change it to `TEXT` or `JSON`?

**Comment by jeanali** [comment]
Yeah it's working NOW!
I changed the column to JSON type, and it's stored like  `{
	"ar": "جديد",
	"en": "new"
}` that's mean it's OK, right?!

**Comment by ivanvermeyen** [comment]
Nice :) 👍

**Comment by mohamed9581** [comment]
i had the same probleme but in laragon i change mariadb to mysql to change caractere arabic //acs3/ to جديد

**Comment by devmuhammadelalfy** [comment]
thanks @ivanvermeyen you helped me alot
