### ISSUE TITLE
an issue with spatie/laravel-tags

### ISSUE THREAD

**Issue by ctf0** [codezero-be/laravel-unique-translation#2]
am not sure if its an issue with the https://github.com/spatie/laravel-tags package or something is missing from the validation package,

but here is what i have
```php
$request->validate([
    'name.*' => 'unique_translation:tags,name,' . $id
]);
```

the db name column i will update is
```
{"en": "black"}
```

and will be replaced with
```
{
  "en": "test",
  "fr": null
}
```

but i keep getting the error that the item already exists in the db, so maybe u can help me with this one

**Comment by ivanvermeyen** [comment]
Hi,

I can't seem to reproduce this in a test...
This test should cover what you are trying to do:

https://github.com/codezero-be/laravel-unique-translation/blob/3b0f7fcee05b609876045a7b81ecb250e208dabd/tests/UniqueTranslationTest.php#L137-L147

I also tried to create a second dummy model which has a "duplicate" `null` translation, but that didn't throw any error either.


```php
$this->model = Model::create([
    'slug' => [
        'en' => 'slug-en',
        'nl' => 'slug-nl',
    ],
    'name' => [
        'en' => 'name-en',
        'nl' => 'name-nl',
    ],
    'other_field' => 'foobar',
]);

Model::create([
    'slug' => [
        'en' => 'another-slug-en',
        'nl' => 'another-slug-nl',
    ],
    'name' => [
        'en' => 'another-name-en',
        'nl' => null,
    ],
]);

$rules = [
    'slug.*' => "{$this->rule}:{$this->table},slug,{$this->model->id}",
    'name.*' => UniqueTranslationRule::for($this->table)->ignore($this->model->id),
];

$this->createRoute('test-array', $rules);

$this->post('test-array', [
    'slug' => ['en' => 'slug-en', 'nl' => 'slug-nl'],
    'name' => ['en' => 'name-en', 'nl' => null],
])->assertStatus(200);
```

Can you give me some more info/code to investigate?

**Comment by ctf0** [comment]
thanx for the test 👍 

> Can you give me some more info/code to investigate?

its a package am building to facilitate working with the spatie/tags, once done i will ping u to test directly on it.

**update**

it seems that `spatie/laravel-tags` allow having duplicates because of types, so will close this for now, thanx again for ur help 🏆
