### ISSUE TITLE
MariaDB / PostgreSQL compatibility

### ISSUE THREAD

**Issue by mahfoudfx** [codezero-be/laravel-unique-translation#21]
Hello,
I'm using this package with MariaDB 10.6.9, Laravel 9, PHP 8.1 and Spatie Laravel Translatable v6, but it is not working.
Is it compatible with this environment or only compatible only with MySQL?
Thanks.

**Comment by ivanvermeyen** [comment]
This package uses a LIKE query so I think it should work...
I never used MariaDB though.
