### ISSUE TITLE
Does not work for PostgreSQL v15

### ISSUE THREAD

**Issue by zdravstvuy1714** [codezero-be/laravel-unique-translation#24]
.env
![image](https://user-images.githubusercontent.com/44904076/216770206-c0146993-2b67-4b32-a64b-e7cef5745013.png)

database config
![image](https://user-images.githubusercontent.com/44904076/216770221-caece8bd-9b0c-4e47-adda-5364acf37f58.png)

validation rule
![image](https://user-images.githubusercontent.com/44904076/216770244-dab84670-a127-41ee-92eb-c4da89017534.png)

result
![image](https://user-images.githubusercontent.com/44904076/216770262-1d33cb79-a399-4662-9e52-b29bd3d3d633.png)

**In the end, I settled on using version 3.5.0. It would be nice to have this fixed for 4 ver.**

**Comment by ivanvermeyen** [comment]
Hi, 

Thanks for reporting this.
The cause of this issue is probably the same as #23.

I never used other databases than MySQL and SQLite, so I'm not exactly experienced with PostgreSQL.
I do know that even SQLite doesn't support the JSON syntax.
Maybe this is also the case for PostgreSQL?

I would be happy to improve compatibility, but I'll need some help with that.

**Comment by ivanvermeyen** [comment]
Can you see if it works with 4.1.0?
Changed back to a LIKE query instead of JSON syntax.
https://github.com/codezero-be/laravel-unique-translation/releases/tag/4.1.0

**Comment by zdravstvuy1714** [comment]
Yes, the bug has been fixed in version 4.1.0 of the package for PostgreSQL 15. Thank you!

**Comment by zdravstvuy1714** [comment]
It is possible to make a slight improvement, depending on the database (MySQL or PostgreSQL) to use LIKE when using MySQL, and ILIKE when using PostgreSQL at findTranslation method:
![image](https://user-images.githubusercontent.com/44904076/216776348-4ccec043-a216-4490-ad7f-838bddb7aadb.png)

**Comment by ivanvermeyen** [comment]
Thanks, I will add this 👍

**Comment by ivanvermeyen** [comment]
Tagged in 4.1.2 🚀
