### ISSUE TITLE
Is compatible with Astrotomic/laravel-translatable?

### ISSUE THREAD

**Issue by xSirLalo** [codezero-be/laravel-unique-translation#28]
I am using the [Astrotomic/Laravel-Translatable](https://github.com/Astrotomic/laravel-translatable) package for the translation of my content through the models, but for me to validate with this package it is as follows

```
"es_name"     => [
    "required_without:en_name,en_slug,en_extract,en_body",
    "required_with:es_slug",
    Rule::unique("blog_post_translations", "name")->where(function ($query) {
        return $query->where("locale", "es");
    }),
],
"es_slug"     => [
    "required_without:en_name,en_slug,en_extract,en_body",
    "required_with:es_name",
    Rule::unique("blog_post_translations", "slug")->where(function ($query) {
        return $query->where("locale", "es");
    }),
],
```

I see that the use of this package makes this validation much easier

**Comment by ivanvermeyen** [comment]
Hi,

This package was originally created to work with [spatie/laravel-translatable](https://github.com/spatie/laravel-translatable).
It uses a single JSON database column for all translations of a specific field.

The Astrotomic translation package uses a separate database table for translations and a column for each locale and field.

So at the moment I'm afraid it's not compatible at all.

I will leave this issue open though.
Maybe we can add compatibility later.
