### ISSUE TITLE
Ignore deleted_at soft deteled field

### ISSUE THREAD

**Issue by cubiczx** [codezero-be/laravel-unique-translation#4]
How can I ignore soft deleted records?
```
'FIELD_NAME.*' => [
UniqueTranslationRule::for('TABLE_NAME', 'FIELD_NAME')->ignore(!0, 'deleted_at') -> NO WORKS
UniqueTranslationRule::for('TABLE_NAME', 'FIELD_NAME')->ignore(!NULL, 'deleted_at') -> NO WORKS
UniqueTranslationRule::for('TABLE_NAME', 'FIELD_NAME')->whereNull('deleted_at') -> NO WORKS
]
```

**Comment by ivanvermeyen** [comment]
Right now, you can't use custom where clauses.
But I will see if I can refactor things to allow for this.

**Comment by cubiczx** [comment]
Thanks, I'm waiting for the fix.
For the moment I understood that it does not work with soft delete.

**Comment by ivanvermeyen** [comment]
Hi,

You should now be able to use 4 new`where` methods on the `UniqueTranslationRule`:

- `where('column', 'value')`
- `whereNot('column', 'value')`
- `whereNull('column')`
- `whereNotNull('column')`

For now you can [review the tests](https://github.com/codezero-be/laravel-unique-translation/blob/master/tests/WhereClauseTest.php) and pull in the dev version to try it out... I will update the docs and tag a release tomorrow.

Hope this helps! :)

**Comment by ivanvermeyen** [comment]
Tagged and released 👍

**Comment by cubiczx** [comment]
Thank you very much!
Works Fine

**Comment by vadykoo** [comment]
@ivanvermeyen Cool, thanks
and thank you for supporting Ukraine!
