### ISSUE TITLE
Too many messages

### ISSUE THREAD

**Issue by cugrif** [codezero-be/laravel-unique-translation#5]
Hi
Thanks for your  extension.

I have some trouble.

Example
```html
<input type="text" name="post_name[de]">
<input type="text" name="post_name[en]">
```
```php
class MyRequest extends FormRequest{
  public function rules(): array
    {
        return [
            'post_name.*' => [
                UniqueTranslationRule::for('posts', 'name')
            ]
        ];
}}
```
When i put exists values and submit form,  i got a lot of messages:
![screenshot](https://i.imgur.com/hZXUSqS.png)

Is there any way to generate only one message for each language?

Best regards

**Comment by ivanvermeyen** [comment]
Hi,

I see your point :)
This behavior was actually a request some time ago (https://github.com/codezero-be/laravel-unique-translation/issues/1).
But there may well be a decent solution to handle both use cases.
I'll have to dig back in and think about how to do this though.

**Comment by Xinecraft** [comment]
If we use something like https://formvuelar.netlify.com/ this bug will get annoying and hard to fix I think from the frontend side.

**Comment by ivanvermeyen** [comment]
Hello,

I agree that always returning both single and array error messages is not optimal after all and it's also not how Laravel handles form errors by default.

I will revert back to only returning relevant messages and try to work out some option to change the behavior for use cases as described in #1 by @ctf0) .

This will need to be a new major version, since it might have an impact on existing implementations.

**Comment by ivanvermeyen** [comment]
I pushed [an update](https://github.com/codezero-be/laravel-unique-translation/commit/fd218766824b7be099c0c1bd2d32f0f78a30ebfa) to `dev-master` that uses Laravel's default behavior.
Only one error will be returned per form attribute:

Form Field | Validation Rule | Error Key
-------------|-----------|-------------
`slug`           | `'slug' => 'unique_translation:table,column'` | `slug`    |
`slug[en]`   | `'slug.*' => 'unique_translation:table,column'` | `slug.en`|

If you could try or review it, I will tag a new release and then see if I can add some options for extra error messages... 👌

**Comment by ivanvermeyen** [comment]
Tagged in 3.0.0 👍
